[build-system]
requires = ["setuptools>=75.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jet-ai-sdk"
version = "0.4.0"
description = "Jet: High-level fine-tuning SDK with engine isolation (HF/Unsloth) and fast CLI"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Jet Team"}]
dependencies = [
  "transformers>=4.42",
  "datasets>=2.18",
  "evaluate>=0.4.3",
  "trl>=0.12.0",
  "unsloth>=0.9.0",
  "bitsandbytes>=0.43.0",
  "mlflow>=2.12",
]

[project.scripts]
jet = "jet.cli:main" # call a function; don't risk shadowing a Typer app object [web:520][web:958]

[project.optional-dependencies]
cli = ["typer>=0.12", "rich>=13", "questionary>=2.0"]  # PEP 621 standard form [web:948][web:952]

[tool.setuptools]
package-dir = {"" = "src"}  # keep

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]            # was ["jet", "jet.*"]; relax to find your code reliably
namespaces = false
